---
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.3
  RubyInterpreters:
    - ruby
    - rake
  Include:
    - "**/*.rb"
    - "**/*.gemfile"
    - "**/*.gemspec"
    - "**/*.rake"
    - "**/*.ru"
    - "**/*.spec"
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/Vagrantfile"
  Exclude:
    - commonlib/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
    - ".git/**/*"
  DisplayCopNames: false
  StyleGuideCopsOnly: false
  DisabledByDefault: true

#################### Layout ####################

Layout/AccessModifierIndentation:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: true

Layout/AssignmentIndentation:
  Enabled: true

Layout/BlockAlignment:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  EnforcedStyle: no_empty_lines
  Exclude:
    - spec/**/*

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EndAlignment:
  Enabled: true

Layout/EndOfLine:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  Exclude:
    - Gemfile

Layout/IndentationWidth:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 80
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoreCopDirectives: false
  IgnoredPatterns:
    - "^\\s*it\\s+.*do$"
    - "^\\s*context\\s+.*do$"
    - "^\\s*describe\\s+.*do$"
    - "^\\s*class\\s+[A-Z].*<.*"

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/ParameterAlignment:
  Enabled: true

Layout/RescueEnsureAlignment:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/Tab:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

#################### Lint ####################

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EndInMethod:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/FlipFlop:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/IneffectiveAccessModifier:
  Enabled: true

Lint/InheritException:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/NextWithoutAccumulator:
  Enabled: true

Lint/NonLocalExitFromIterator:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/PercentStringArray:
  Enabled: true

Lint/PercentSymbolArray:
  Enabled: true

Lint/RandOne:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantSplatExpansion:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/SuppressedException:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: false

Lint/UselessComparison:
  Enabled: false

Lint/UselessElseWithoutRescue:
  Enabled: false

Lint/UselessSetterCall:
  Enabled: false

Lint/Void:
  Enabled: false

#################### Metrics ####################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

#################### Naming ####################

Naming/AccessorMethodName:
  Enabled: true

Naming/AsciiIdentifiers:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/PredicateName:
  Enabled: true

Naming/VariableName:
  Enabled: true

#################### Performance ####################

Performance/CaseWhenSplat:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/Count:
  SafeAutoCorrect: true
  Enabled: false

Performance/Detect:
  SafeAutoCorrect: true
  Enabled: false

Performance/DoubleStartEndWith:
  Enabled: false

Performance/EndWith:
  Enabled: false

Performance/FixedSize:
  Enabled: false

Performance/FlatMap:
  Enabled: false
  EnabledForFlattenWithoutParams: false

Performance/RangeInclude:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Performance/RedundantMerge:
  Enabled: true

Performance/ReverseEach:
  Enabled: false

Performance/Size:
  Enabled: false

Performance/StartWith:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Performance/TimesMap:
  Enabled: false

#################### Rails ####################

Rails/ActionFilter:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/Exit:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/PluralizationGrammar:
  Enabled: false

Rails/ReadWriteAttribute:
  Enabled: false

Rails/RequestReferer:
  Enabled: false

Rails/ScopeArgs:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/UniqBeforePluck:
  Enabled: false

Rails/Validation:
  Enabled: false

#################### Security ####################

Security/Eval:
  Enabled: false

#################### Style ####################

Style/Alias:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: false

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/BlockDelimiters:
  Enabled: false
  Exclude:
    - spec/**/*

Style/CaseEquality:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/Documentation:
  Enabled: true
  Exclude:
    - db/migrate/*
    - spec/**/*
    - test/**/*

Style/DoubleNegation:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EachWithObject:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/Encoding:
  Enabled: false

Style/EndBlock:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/For:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
  Exclude:
    - config/routes.rb

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/IfUnlessModifierOfIfUnless:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/InfiniteLoop:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/LambdaCall:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedModifier:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: true

Style/NonNilCheck:
  Enabled: true

Style/Not:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/OneLineConditional:
  Enabled: false

Style/OptionalArguments:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PercentQLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: true

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantCapitalW:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: false

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantSortBy:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: true

Style/Sample:
  Enabled: false

Style/SelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SignalException:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StructInheritance:
  Enabled: true

Style/SymbolLiteral:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/TrailingUnderscoreVariable:
  AllowNamedUnderscoreVariables: true
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/ZeroLengthPredicate:
  Enabled: true
